### ISSUE TITLE
Ubuntu 18.04 support / use official .deb package

### ISSUE THREAD

**Issue by mpdude** [jdowning/puppet-awscli#60]
Is this module still maintained and if so, would you support installing the Ubuntu `awscli` [package](https://packages.ubuntu.com/bionic/awscli) as a `.deb` instead of the `pip` variant?

If you're still maintaining this module, I could try to come up with a PR.

**Comment by jdowning** [comment]
Hi @mpdude. Yes I still maintain this module, though development has slowed quite a bit. If you have a PR to give users the ability to install a Debian package (while still maintaining the `pip` option), I would certainly consider merging it.

**Comment by mpdude** [comment]
See #61 please.

**Comment by mpdude** [comment]
Merged in #61.
