### ISSUE TITLE
module dependencies

### ISSUE THREAD

**Issue by Vinclame** [jdowning/puppet-awscli#66]
stdlib and concat are already on version > 6. Please update metadata.json

**Comment by jdowning** [comment]
😕 I'm not sure I understand?

**Comment by Vinclame** [comment]
Looks good now in version 2.2.0. Thanks!

version 2.1.0 had some conflicting dependencies:
puppetlabs/stdlib (>= 4.0.0 <5.0.0)
puppetlabs/concat (>= 2.0.0 <5.0.0)

Because my setup already was using stdlib and concat version 6, this was blocking the installation (with puppet module install).
